//
//  AnalyticsEvents.swift
//  boxpay-ios-checkout-sdk
//
//  Created by Ishika Bansal on 03/09/25.
//

public enum AnalyticsEvents: String {
    // ui event
    case ADDRESS_UPDATED = "ADDRESS_UPDATED"
    case PAYMENT_CATEGORY_SELECTED = "ENABLE_TEST_ENV"
    case PAYMENT_METHOD_SELECTED = "PAYMENT_METHOD_SELECTED"
    case PAYMENT_INITIATED = "PAYMENT_INITIATED"
    case CHECKOUT_LOADED = "CHECKOUT_LOADED"
    case PAYMENT_INSTRUMENT_PROVIDED = "PAYMENT_INSTRUMENT_PROVIDED"
    case UPI_APP_NOT_FOUND = "UPI_APP_NOT_FOUND"
    case FAILED_TO_LAUNCH_UPI_INTENT = "FAILED_TO_LAUNCH_UPI_INTENT"
    case ERROR_GETTING_UPI_URL = "ERROR_GETTING_UPI_URL"
    case SDK_CRASH = "SDK_CRASH"
    case PAYMENT_RESULT_SCREEN_DISPLAYED = "PAYMENT_RESULT_SCREEN_DISPLAYED"
}
